name: Generate Blog List

on:
  schedule:
    - cron: "0 0 * * SAT"
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  blog:
    runs-on: ubuntu-latest
    name: Fetch and Generate Blog Posts
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate
        uses: ErrorGamer2000/github-readme-blog-post-action@v1
        with:
          feed_urls: https://pthoor.github.io/feed.xml
          max_posts_per_url: 5
          show_feed_data: true
          output_dir: blog-posts
          locale: en-US
          time_zone: UTC
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save Generated Blog Posts
          skip_checkout: true
